name: "My Docker Action"
description: "Example of passing inputs as env vars"

inputs:
  username:
    description: "User name to print"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.username }}
